name: conan
on:
  # push:
  #  branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          pip install conan
          conan profile detect
          conan install --requires xkbcommon/1.6.0 -b xkbcommon/1.6.0 -of 1 \
            -o 'libiconv/*:shared=True' -c tools.system.package_manager:mode=install

      - name: conan list
        #shell: bash
        run: |
          set -x
          conan list -f compact | tail -n +2

      - name: Upload a Build Artifact
        if: false
        uses: actions/upload-artifact@v4.6.1
        with:
          path: |
            *.json
            *.tgz
            conan.lock
