name: conan
on:
  # push:
  #  branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          pip install conan
          conan profile detect
          conan install --requires freetype/2.13.2 -pr default -b missing --lockfile-out conan.lock -of 1

      - name: Run conan
        shell: bash
        run: |
          set -x
          conan list -f compact | tail -n +2
          conan graph info --requires freetype/2.13.2 -pr default -f json --build=never --no-remote --filter=context > graph_context.json
          #cat graph_context.json
          conan list \
            --graph graph_context.json \
            --graph-context=build-only \
            --format=json \
            > pkglist.json
          exit 0
          buildPackages=$(jq -rb '.graph.nodes[] | select(.context == "build") | .ref' graph_context.json | sort | uniq)
          printf '%s' $buildPackages | xxd
          printf '%s' "$buildPackages" | xxd
          for p in $buildPackages ; do
            echo "'$p'"
            conan remove --confirm "$p:*"
          done

          #conan graph info --requires freetype/2.13.2 -f json --build=never --out-file graph.json --no-remote
          #jq -c 'del(.graph.nodes[] | select(.context == "host"))' graph.json > graph_build.json
          #conan list -f json --out-file list.json -c -g graph_build.json
          #conan remove --confirm -l list.json
          conan cache clean
          conan cache save --file cache_all.tgz '*:*'

          #jq -c 'del(.graph.nodes[] | select(.context == "build"))' graph.json > graph_host.json
          #conan list -f json --out-file list.json -c -g graph_host.json
          #conan cache save --file cache_all.tgz -l list.json

      - name: Upload a Build Artifact
        if: always()
        uses: actions/upload-artifact@v4.6.1
        with:
          path: |
            *.json
            *.tgz
            conan.lock
