name: conan
on:
  # push:
  #  branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          pip install conan
          conan profile detect

          xkbVersion=1.13.1
          #xkbVersion=1.6.0
          conan install -of 1 --requires xkbcommon/$xkbVersion -b xkbcommon/$xkbVersion -b wayland/1.24.0 -o '*:shared=True' \
            -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True

      - name: conan list
        #shell: bash
        run: |
          set -x
          conan list -f compact | tail -n +2

      - name: Upload a Build Artifact
        if: false
        uses: actions/upload-artifact@v4.6.1
        with:
          path: |
            *.json
            *.tgz
            conan.lock
