name: Notify other repos of release
on:
  release:
    types: [published]
jobs:
  notify_repos:
    if: ${{ !github.event.release.prerelease }}
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch only for releases
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.EXT_REPO_PAT }}
          repository: kambala-decapitator/repository_dispatch_test
          event-type: on-release
          client-payload: '{"release": ${{ toJson(github.event.release) }}}'
