name: CI
on:
  workflow_dispatch:
    inputs:
      newVersion:
        type: string
        description: 'Release version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: ncipollo/release-action@v1
        id: release
        with:
          tag: ${{ inputs.newVersion }}
          draft: true

      - name: release outputs
        run: echo ${{ steps.release.outputs.id }} '${{ steps.release.outputs.upload_url }}'

      - name: create artifact
        run: sleep 30 ; date > 1.txt

      - name: add artifact
        run: |
          uploadURL=$(sed 's/{?name,label}/?name=myfile.txt/')
          echo "$uploadURL"
          curl -d @1.txt -H 'Content-Type: application/octet-stream' -H 'Authorization: token ${{ github.token }}' "$uploadURL"

      - uses: ncipollo/release-action@v1
        name: publish release
        with:
          allowUpdates: true
          tag: ${{ inputs.newVersion }}
          draft: false
