name: CI
on:
  workflow_dispatch:
    inputs:
      newVersion:
        type: string
        description: 'Release version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: ncipollo/release-action@v1
        id: release
        with:
#           allowUpdates: true
          tag: ${{ inputs.newVersion }}
#           commit: main
          draft: true

      - name: release outputs
        run: echo ${{ steps.release.outputs.id }} ${{ steps.release.outputs.upload_url }}

      - name: create artifact
        run: sleep 30 ; date > 1.txt
        
      - name: add artifact
        run: 'curl -d @1.txt -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ github.token }}" ${{ steps.release.outputs.upload_url }}'

      - uses: ncipollo/release-action@v1
        name: publish release
        with:
          allowUpdates: true
          tag: ${{ inputs.newVersion }}
          draft: false
