name: CI
on:
  workflow_dispatch:
    inputs:
      newVersion:
        type: string
        description: 'Release version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: ncipollo/release-action@v1
        id: release
        with:
#           allowUpdates: true
          tag: ${{ inputs.newVersion }}
#           commit: main
          draft: true

      - name: release outputs
        run: echo ${{ steps.release.outputs.id }} ${{ steps.release.outputs.upload_url }}

      - name: create artifact
        run: date > 1.txt

      - uses: tubone24/update_release@v1.3.1
        name: add artifact
        with:
          draft: false
        env:
          TAG_NAME: ${{ inputs.newVersion }}
