name: CI
on:
  workflow_dispatch:
    inputs:
      newVersion:
        type: string
        description: 'Release version'
        required: true
  push:
    tags:
    - '*'
env:
  TAG: ${{ inputs.newVersion || github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - run: |
          echo "env $TAG"
          echo 'literal ${{ env.TAG }}'
        if: github.ref_type == 'tag'
      - uses: ncipollo/release-action@v1
        id: release
        with:
          tag: ${{ env.TAG }}
          draft: true

      - name: release outputs
        run: echo ${{ steps.release.outputs.id }} '${{ steps.release.outputs.upload_url }}'

      - name: create artifact
        run: sleep 10 ; date > 1.txt

      - name: add artifact
        run: |
          set -x
          uploadURL=$(sed 's/{?name,label}/?name=myfile.txt/' <<<'${{ steps.release.outputs.upload_url }}')
          echo "$uploadURL"
          curl -d @1.txt -H 'Content-Type: application/octet-stream' -H 'Authorization: token ${{ github.token }}' "$uploadURL"

      - uses: ncipollo/release-action@v1
        name: publish release
        with:
          allowUpdates: true
          tag: ${{ env.TAG }}
          draft: false
