name: Release from a run

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'The ID of the Actions run to use for artifacts'
        required: true
        type: number

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: asd
        shell: python
        run: |
          import json
          from urllib.request import urlopen, urlretrieve

          artifactsUrl = 'https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.inputs.run_id }}/artifacts'
          with urlopen(artifactsUrl) as response:
              for artifact in json.loads(response.read().decode('utf-8'))['artifacts']:
                  print(artifact['name'])
