name: Release from a run

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'The ID of the Actions run to use for artifacts'
        required: true
        type: number

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LISTS_DIR: lists
      DEPENDENCIES_DIR: deps

    steps:
      - name: Download artifacts
        run: |
          gh --repo vcmi/vcmi-dependencies run download ${{ github.event.inputs.run_id }} --dir "$LISTS_DIR" --pattern 'list of*'
          gh --repo vcmi/vcmi-dependencies run download ${{ github.event.inputs.run_id }} --dir "$DEPENDENCIES_DIR" --pattern 'dependencies-*'
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Create release
        shell: python
        env:
          GH_TOKEN: ${{ github.token }}
          GH_DEBUG: api
        run: |
          from datetime import date
          from glob import glob
          from os import getenv
          from pathlib import Path
          from subprocess import run

          releaseNotes = "Generated from [this](https://github.com/vcmi/vcmi-dependencies/actions/runs/${{ github.event.inputs.run_id }}) Actions run\n"
          asd = sorted(Path(".").glob(getenv("LISTS_DIR") + "/**/*.txt"))
          for packageListPath in asd: # sorted(Path(".").glob(getenv("LISTS_DIR") + "/**/*.txt")):
              releaseNotes += f""" \
          <details><summary><b>{packageListPath.stem.removeprefix("dependencies-")}</b> packages</summary>

          {open(packageListPath, "r").read()}
          </details>
              """

          tag = str(date.today())
          dependencies = glob(getenv("DEPENDENCIES_DIR") + "/**/*.tgz")
          print(["gh", "release", "create", tag, "--prerelease", "--notes", releaseNotes] + dependencies)
          run(["gh", "release", "create", tag, "--prerelease", "-d", "--notes", releaseNotes] + asd)
