name: windows
on:
  # push:
  #  branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    # runs-on: windows-11-arm
    defaults:
      run:
        shell: bash
    steps:
      - run: |
          pip install conan
          conan profile detect
          set -x
          conan download "onnx/1.16.2#4a04f9b46667120c6db25d1a207172bd"
          conan download "onnx/1.16.2#b380f30b8d3e38d38fb8af64e6f24ae4"
        #shell: cmd

      # - uses: actions/checkout@v4

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ffmpeg-build-dir
      #     compression-level: 0
      #     path: |
      #       ${{ env.CONAN_HOME }}/p/b/ffmp*/b/build-release
