name: windows
on:
  # push:
  #  branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    # runs-on: windows-latest
    runs-on: windows-2025-vs2026
    defaults:
      run:
        shell: bash
    steps:
      - run: |
          pip install conan
          conan profile detect
        #shell: cmd
        
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          repository: kambala-decapitator/conan-center-index
          ref: package/libvpx
          path: cci
          sparse-checkout: recipes/libvpx

      - run: |
          conan create cci/recipes/libvpx/all --version 1.16.0 -b missing
          
      # - uses: actions/checkout@v6

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ffmpeg-build-dir
      #     compression-level: 0
      #     path: |
      #       ${{ env.CONAN_HOME }}/p/b/ffmp*/b/build-release
